---
# tasks file for elk

- name: Install java
  yum:
    name: java-11-openjdk-devel
    state: present
    update_cache: yes

- name: Install elastic search repo
  yum_repository:
    name: Elastic_7.X.repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastoc.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.X repo

- name: install gpg key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install elastic search
  yum:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Update config file for access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Update config file
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: Start elastic search
  service:
    name: elasticsearch
    state: started

- name: Install logstash repo
  yum_repository:
    name: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: elastic 7.x packages repo

- name: Install logstasg
  yum:
    name: logstash
    state: present
    update_cache: yes

- name: Update config file
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: 'http.host: 127.0.0.1'

- name: Start logstash
  service:
    name: logstash
    state: started

- name: Install kibana repo
  yum_repository:
    name: Kibana 7.x packages
    baseurl: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Kibana 7.x

- name: Install kibana
  yum:
    name: kibana
    state: present
    update_cache: yes

- name: Update config for access
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: 0.0.0.0'

- name: Update config file
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Start kibana
  service:
    name: kibana
    state: started
    
    
