---
# tasks file for clonerepo

- name: Git installation on debian
  apt:
    name: git
    state: latest
  when: ansible_distribution == "Debian"

- name: Git installation on centos
  yum:
    name: git
    state: latest
  when: ansible_distribution == "CentOS"

- name: Git installation on opensuse
  zypper:
    name: git
    state: latest
  when: ansible_distribution == "openSUSE Tumbleweed"

- name: Clone prelim exam repository
  git:
    repo: '{{ prelim-exam }}'
    dest: ./prelim-exam
    version: prelim-exam


