---
# tasks file for elk

- name: Installing pre req for elastic search
  apt:
    name:
      - openjdk-11-jdk
      - nginx
    state: latest
    update_cache: yes

- name: Add elastic repo
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Install apt repo
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Get apt transport https
  apt:
    name: apt-transport-https
    state: present

- name: Install elastic search
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Update config  file
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host'
    line: 'network.host: localhost'

- name: Update port
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port'
    line: 'http.port: 9200'

- name: Discovery type
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.type: single-node'

- name: Start elastic search
  service:
    name: elasticsearch
    state: started

- name: Install kibana
  apt:
    name: kibana
    update_cache: yes

- name: Update config file
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.host: localhost'

- name: Define server port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port'
    line: 'server.port: 5601'

- name: Start kibana
  service:
    name: kibana
    state: started

- name: Install logstash
  apt:
    name: logstash
    update_cache: yes

- name: Start logstash
  service:
    name: logstash
    state: started
  
