---
# tasks file for grafana

- name: install prereq packages for grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
    register: pkg_grafana
    
- name: Depackage grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: Install libfont
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Start grafana
  service:
    name: grafana-server
    state: started

- name: Install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: Start prometheus
  service:
    name: prometheus
    state: started

- name: Add influxdata key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add influxdata repo
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntufocal stable'
    state: present

- name: Install influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: yes

- name: Start influxdb
  service:
    name: influxdb
    state: started
