---
# tasks file for lamp

- name: Install apache
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Add apache index
  copy:
    content: "Hello World"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index

- name: Start apache2 service
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: apache_index.changed

- name: Whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Install mysql-server
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Add mysql index
  copy:
    content: "Hi world"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: Start mysql service
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: mysql_index.changed

- name: Install php
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: Add php index
  copy:
    content: 'qgarnaldo'
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
